name              'nettyapp'
maintainer        "Fuel Powered Inc"
maintainer_email  "shea@fuelpowered.com"
license           "Apache 2.0"
description       "Install and deploy gradle-based netty servers."
version           "0.0.1"
recipe            "nettyapp::configure", "This recipe configures nettyapp in OpsWorks stack"
recipe            "nettyapp::deploy", "This recipe deploys the nettyapp in OpsWorks stack"
recipe            "nettyapp::restart", "This recipe restarts the nettyapp in OpsWorks stack"
recipe            "nettyapp::rollback", "This recipe rolls back a deploy in OpsWorks stack"
recipe            "nettyapp::stop", "This recipe stops nettyapp in OpsWorks stack"
recipe            "nettyapp::undeploy", "This recipe undeploys app from OpsWorks stck"
depends           "gradle"
depends           "monit"
depends           "java"
